# Configurations for the PollyNET campaign
# Those configuration will be used as the global attributes in the netCDF file for EARLINET.
#
# History:
#   2019-09-12 First edition by Zhenping

institution = "Leibniz-Institut für Troposphärenforschung e.V."

PI = "Dietrich Althausen"
PI_affliliation = "Leibniz-Institut für Troposphärenforschung e.V."
PI_affiliation_acronym = "TROPOS"
PI_address = "Permoserstraße 15, 04103 Leipzig, Germany"
PI_phone = ""
PI_email = "dietrich@tropos.de"

Data_Originator = "Holger Baars"
Data_Originator_affliliation = "Leibniz-Institut für Troposphärenforschung e.V."
Data_Originator_affiliation_acronym = "TROPOS"
Data_Originator_address = "Permoserstraße 15, 04103 Leipzig, Germany"
Data_Originator_phone = ""
Data_Originator_email = "baars@tropos.de"

data_processing_institution = "Leibniz-Institut für Troposphärenforschung e.V."

scc_version = ""
scc_version_description = ""
processor_name = ""
processor_version = ""

title = "Profiles of aerosol optical properties"
source = "Ground based LIDAR measurements"
station_ID = "dus"
station_latitude = 38.56   # negative for southern hemisphere
station_longitude = 68.86   # negative for west
station_altitude = 864   # [m]
station_starttime = "2015-03-17 00:00:00"
station_endtime = "2016-09-30 00:00:00"
comment = "Central Asian dust measurements"
references = "Project website at http://www.earlinet.org"

__file_format_version = "2.0"
Conventions = "CF-1.7"
hoi_system_ID = -1
hoi_configuration_ID = -1