# Configurations for the PollyNET campaign
# Those configuration will be used as the global attributes in the netCDF file for EARLINET.
#
# History:
#   2019-09-12 First edition by Zhenping

institution = "National Observatory of Athens - NOA"

PI = "Vassilis Amiridis"
PI_affiliation = "National Observatory of Athens"
PI_affiliation_acronym = "NOA"
PI_address = "Vas. Pavlou & I. Metaxa, 15236 Penteli, Greece"
PI_phone = "2108109116"
PI_email = "vamoir@noa.gr"

Data_Originator = "Holger Baars"
Data_Originator_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
Data_Originator_affiliation_acronym = "TROPOS"
Data_Originator_address = "Permoserstraße 15, 04103 Leipzig, Germany"
Data_Originator_phone = ""
Data_Originator_email = "baars@tropos.de"

data_processing_institution = "Leibniz Institute for Tropospheric Research, Leipzig"

scc_version = ""
scc_version_description = ""
processor_name = ""   # if this was set empty, the program will add the processor automatically based on the labview version or Picasso version
processor_version = ""

title = "Profiles of aerosol optical properties"
source = "Ground based LIDAR measurements"
station_ID = "fik"
station_latitude = 35.34   # negative for southern hemisphere
station_longitude = 25.67   # negative for west
station_altitude = 238   # [m]
station_starttime = "2017-02-25 00:00:00"
station_endtime = "2018-05-31 00:00:00"
comment = "Finokalia, Greece"
references = "Project website at http://www.earlinet.org"

__file_format_version = "2.0"
Conventions = "CF-1.7"
hoi_system_ID = -1
hoi_configuration_ID = -1