# Configurations for the PollyNET campaign
# Those configuration will be used as the global attributes in the netCDF file for EARLINET.
#
# History:
#   2019-09-23 First edition by Zhenping

institution = "Leibniz Institute for Tropospheric Research, Leipzig"

PI = "Dietrich Althausen"
PI_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
PI_affiliation_acronym = "TROPOS"
PI_address = "Permoserstraße 15, 04103 Leipzig, Germany"
PI_phone = ""
PI_email = "dietrich@tropos.de"

Data_Originator = "Julian Hofer"
Data_Originator_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
Data_Originator_affiliation_acronym = "TROPOS"
Data_Originator_address = "Permoserstraße 15, 04103 Leipzig, Germany"
Data_Originator_phone = ""
Data_Originator_email = "hofer@tropos.de"

data_processing_institution = "Leibniz Institute for Tropospheric Research, Leipzig"

scc_version = ""
scc_version_description = ""
processor_name = ""   # if this was set empty, the program will add the processor automatically based on the labview version or Picasso version
processor_version = ""

title = "Profiles of aerosol optical properties"
source = "Ground based LIDAR measurements"
station_ID = "hai"
station_latitude = 32.78   # negative for southern hemisphere
station_longitude = 35.00   # negative for west
station_altitude = 0   # [m]
station_starttime = "2016-07-24 00:00:00"
station_endtime = "2019-05-12 00:00:00"
comment = "Technion area at Haifa, Israel"
references = "Project website at http://www.earlinet.org"

__file_format_version = "2.0"
Conventions = "CF-1.7"
hoi_system_ID = 146
hoi_configuration_ID = 478