# Configurations for the PollyNET campaign
# Those configuration will be used as the global attributes in the netCDF file for EARLINET.
#
# History:
#   2019-09-12 First edition by Zhenping

institution = "DWD Meteorological Observatory Hohenpeissenberg"

PI = "Ina Mattis"
PI_affiliation = "Deutscher Wetterdienst Observatorium Hohenpeißenberg"
PI_affiliation_acronym = "DWD"
PI_address = "Albin-Schwaiger-Weg 10, 82383 Hohenpeißenberg"
PI_phone = ""
PI_email = "ina.mattis@dwd.de"

Data_Originator = "Holger Baars"
Data_Originator_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
Data_Originator_affiliation_acronym = "TROPOS"
Data_Originator_address = "Permoserstraße 15, 04103 Leipzig, Germany"
Data_Originator_phone = ""
Data_Originator_email = "baars@tropos.de"

data_processing_institution = "Leibniz Institute for Tropospheric Research, Leipzig"

scc_version = ""
scc_version_description = ""
processor_name = "PollyNET version 1.3"
processor_version = "1.3"

title = "Profiles of aerosol optical properties"
source = "Ground based LIDAR measurements"
station_ID = "hpb"
station_latitude = 47.80   # negative for southern hemisphere
station_longitude = 11.01   # negative for west
station_altitude = 974   # [m]
station_starttime = "2015-09-12 00:00:00"
station_endtime = "2099-01-01 00:00:00"
comment = "Hohenpeissenberg, Germany"
references = "Project website at http://www.earlinet.org"

__file_format_version = "2.0"
Conventions = "CF-1.7"
hoi_system_ID = -1
hoi_configuration_ID = -1