# Configurations for the PollyNET campaign
# Those configuration will be used as the global attributes in the netCDF file for EARLINET.
#
# History:
#   2019-09-23 First edition by Zhenping

institution = "Leibniz Institute for Tropospheric Research, Leipzig"

PI = "Ronny Engelmann"
PI_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
PI_affiliation_acronym = "TROPOS"
PI_address = "Permoserstraße 15, 04103 Leipzig, Germany"
PI_phone = ""
PI_email = "ronny@tropos.de"

Data_Originator = "Holger Baars"
Data_Originator_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
Data_Originator_affiliation_acronym = "TROPOS"
Data_Originator_address = "Permoserstraße 15, 04103 Leipzig, Germany"
Data_Originator_phone = ""
Data_Originator_email = "baars@tropos.de"

data_processing_institution = "Leibniz Institute for Tropospheric Research, Leipzig"

scc_version = ""
scc_version_description = ""
processor_name = ""   # if this was set empty, the program will add the processor automatically based on the labview version or Picasso version
processor_version = ""

title = "Profiles of aerosol optical properties"
source = "Ground based LIDAR measurements"
station_ID = "kos"
station_latitude = 49.57   # negative for southern hemisphere
station_longitude = 15.08   # negative for west
station_altitude = 535   # [m]
station_starttime = "2017-08-14 00:00:00"
station_endtime = "2017-11-10 00:00:00"
comment = "ACTRIS flux measurement campaign at National atmospheric observatory Košetice"
references = "Project website at http://www.earlinet.org"

__file_format_version = "2.0"
Conventions = "CF-1.7"
hoi_system_ID = 91
hoi_configuration_ID = 297