# Configurations for the PollyNET campaign
# Those configuration will be used as the global attributes in the netCDF file for EARLINET.
#
# History:
#   2019-09-12 First edition by Zhenping

institution = "Finnish Meteorological Institute"

PI = "Mika Komppula"
PI_affiliation = "Finnish Meteorological Institute"
PI_affiliation_acronym = "FMI"
PI_address = "Erik Palménin aukio 1, FI-00560 HELSINKI"
PI_phone = ""
PI_email = "mika.komppula@fmi.fi"

Data_Originator = "Holger Baars"
Data_Originator_affiliation = "Leibniz Institute for Tropospheric Research, Leipzig"
Data_Originator_affiliation_acronym = "TROPOS"
Data_Originator_address = "Permoserstraße 15, 04103 Leipzig, Germany"
Data_Originator_phone = ""
Data_Originator_email = "baars@tropos.de"

data_processing_institution = "Leibniz Institute for Tropospheric Research, Leipzig"

scc_version = ""
scc_version_description = ""
processor_name = ""   # if this was set empty, the program will add the processor automatically based on the labview version or Picasso version
processor_version = ""

title = "Profiles of aerosol optical properties"
source = "Ground based LIDAR measurements"
station_ID = "kuo"
station_latitude = 62.73   # negative for southern hemisphere
station_longitude = 27.55   # negative for west
station_altitude = 190   # [m]
station_starttime = "2012-10-12 00:00:00"
station_endtime = "2099-01-01 00:00:00"
comment = "Kuopio, Finland"
references = "Project website at http://www.earlinet.org"

__file_format_version = "2.0"
Conventions = "CF-1.7"
hoi_system_ID = -1
hoi_configuration_ID = -1